keys:
  - &jason_whitman 0F1560559B2C5597868B6E68875AFB2B1752E430
  - &server_pc 460c90266ee21d3b0d5282fbbe72e00bcb1351e3
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        - *jason_whitman
        - *server_pc